version: '3.7'

services:

  webApp:
    container_name: webApp-dev
    build: ./site
    image: obaa.io:v1.2
    command: python /usr/src/obaa.io/manage.py runserver 0.0.0.0:8080
#    command: python /usr/src/obaa.io/manage.py runserver 0.0.0.0:8080 --settings=main.settings.production
#    command: /usr/local/bin/gunicorn main.wsgi:application -w 2 -b :8080
    depends_on:
      - db
    env_file: ./site/docker.env
    volumes:
      - ./site/:/usr/src/obaa.io/
    ports:
      - 8080:8080
#    restart: always




#  nginx:
#    build: ./nginx
#    ports:
#      - 8000:80
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#    depends_on:  # <-- wait for web to be "ready" before starting this service
#      - web

  db:
    image: postgres:10.5-alpine
    container_name: webApp-dev-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: