version: '3.7'

services:

  webApp:
    build: ./site
    container_name: webApp
    image: obaa.io:v1.1
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8080
#    command: python /usr/src/obaa.io/manage.py runserver 0.0.0.0:80
    depends_on:
      - db
    expose:
      - 8080
    env_file: ./site/docker.env
    volumes:
      - ./site/:/usr/src/obaa.io/
      - ./static_cdn/static_root/:/usr/src/static_cdn/static_root/
      - static_volume:/usr/src/static_cdn/static_root/

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx:v1.0
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static_cdn/static_root/:/usr/src/static_cdn/static_root/
      - static_volume:/usr/src/static_cdn/static_root/
    depends_on:
      - webApp

  db:
    container_name: webApp_db
    image: postgres:alpine
    env_file: ./site/docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume: