# Generated by Django 2.1.7 on 2019-04-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190402_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMe',
            new_name='ContactMessage',
        ),
    ]
