# Generated by Django 2.1.7 on 2019-02-17 19:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('tags', '0001_initial'),
        ('blog', '0002_auto_20190217_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='BlogPost',
        ),
    ]
